import FreeSimpleGUI as sg
from PIL import Image, ImageEnhance, ImageDraw
import io
import os

def floyd_steinberg_dither(image):
    """
    Applies Floyd-Steinberg dithering to a PIL Image.
    Returns the dithered image in '1' (1-bit) mode.
    """
    # Convert to grayscale first
    img = image.convert('L')
    width, height = img.size
    
    # We load pixels into a list of lists (float-compatible) to avoid
    # "color must be int" errors during error distribution calculation.
    # img.getdata() returns a flat sequence of pixel values.
    flat_data = list(img.getdata())
    pixels = [flat_data[i * width:(i + 1) * width] for i in range(height)]

    for y in range(height):
        for x in range(width):
            old_pixel = pixels[y][x]
            # Threshold at 128
            new_pixel = 255 if old_pixel > 128 else 0
            pixels[y][x] = new_pixel
            
            error = old_pixel - new_pixel

            # Distribute error to neighbors (Floyd-Steinberg kernel)
            # Note: pixels is [y][x] (row, col)
            
            # Right
            if x + 1 < width:
                pixels[y][x + 1] += error * 7 / 16
            # Bottom Left
            if x - 1 >= 0 and y + 1 < height:
                pixels[y + 1][x - 1] += error * 3 / 16
            # Bottom
            if y + 1 < height:
                pixels[y + 1][x] += error * 5 / 16
            # Bottom Right
            if x + 1 < width and y + 1 < height:
                pixels[y + 1][x + 1] += error * 1 / 16

    # Reconstruct the image
    # Flatten the 2D list back to 1D and ensure integers
    new_data = [int(p) for row in pixels for p in row]
    
    out_img = Image.new('L', (width, height))
    out_img.putdata(new_data)
    
    return out_img.convert('1') # Return as 1-bit image

def convert_to_bytes(image):
    """
    Helper to convert PIL image to bytes for FreeSimpleGUI display.
    """
    with io.BytesIO() as bio:
        image.save(bio, format="PNG")
        return bio.getvalue()

def create_svg(image, filepath, dot_size_mm=0.5, color="#000000"):
    """
    Creates an SVG where the physical dimensions are calculated based on the
    desired dot size in millimeters. Uses circles instead of rects.
    """
    width, height = image.size
    pixels = image.load()
    
    # Calculate physical dimensions in mm
    phys_width_mm = width * dot_size_mm
    phys_height_mm = height * dot_size_mm
    
    # We set the SVG width/height to physical mm units.
    # We set the viewBox to the pixel dimensions.
    # This automatically maps 1 coordinate unit -> 1 dot_size_mm.
    svg_content = [
        f'<svg width="{phys_width_mm}mm" height="{phys_height_mm}mm" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">',
        f'<!-- Generated by Python Dither App: {width}x{height} pixels at {dot_size_mm}mm/dot -->'
    ]

    # Body
    for y in range(height):
        for x in range(width):
            # In '1' mode, 0 is black, 1 (or 255) is white
            if pixels[x, y] == 0:
                # Draw a circle.
                # Center is x+0.5, y+0.5 to center it in the grid cell.
                # Radius is set small (0.05) so the plotter treats it as a single point/dot
                # rather than drawing a visible circle circumference.
                circle = f'<circle cx="{x + 0.5}" cy="{y + 0.5}" r="0.05" fill="{color}" />'
                svg_content.append(circle)

    # Footer
    svg_content.append('</svg>')
    
    with open(filepath, 'w') as f:
        f.write("\n".join(svg_content))

def main():
    sg.theme('DarkGrey9')

    layout = [
        [sg.Text("Dither to SVG Converter", font=("Helvetica", 16))],
        
        # File Selection
        # Updated file_types to prioritize "All Files" to prevent OS-specific filtering issues
        [sg.Text("Select Image:"), sg.Input(key="-FILE-", enable_events=True), sg.FileBrowse(file_types=(("All Files", "*.*"), ("JPG", "*.jpg"), ("PNG", "*.png")))],
        
        [sg.HorizontalSeparator()],
        
        # Controls Column
        [sg.Column([
            [sg.Text("Settings", font=("Helvetica", 12, "bold"))],
            
            [sg.Text("Resize Width (px):")],
            [sg.Slider(range=(50, 800), default_value=200, orientation='h', size=(30, 20), key="-WIDTH-", enable_events=True)],
            [sg.Text("Note: Smaller widths make better abstract SVGs", text_color="yellow", font=("Helvetica", 8))],
            
            [sg.Text("Contrast:")],
            [sg.Slider(range=(0.5, 3.0), default_value=1.0, resolution=0.1, orientation='h', size=(30, 20), key="-CONTRAST-", enable_events=True)],
            
            [sg.Button("Process Preview", size=(20, 2), button_color=("white", "#007acc"))],
            [sg.HorizontalSeparator()],
            [sg.Text("SVG Output Settings", font=("Helvetica", 12, "bold"))],
            # Changed label to reflect physical units
            [sg.Text("Pen/Dot Diameter (mm):"), sg.Input("0.5", size=(5,1), key="-DOT_MM-")],
            [sg.Button("Save SVG", size=(20, 2), button_color=("white", "green"), disabled=True, key="-SAVE-")]
        ], vertical_alignment='top'),
         
         # Preview Column
         sg.VSeparator(),
         sg.Column([
             [sg.Text("Preview:")],
             [sg.Image(key="-IMAGE-", size=(400, 400), background_color='black')]
         ], element_justification='center', expand_x=True, expand_y=True)
        ]
    ]

    window = sg.Window("Dither Master", layout, resizable=True)

    # State variables
    current_original_image = None
    current_dithered_image = None

    while True:
        event, values = window.read()

        if event == sg.WIN_CLOSED:
            break

        # 1. Load Image
        if event == "-FILE-" and values["-FILE-"]:
            filename = values["-FILE-"]
            if os.path.exists(filename):
                try:
                    # Open and keep a reference to the original
                    pil_image = Image.open(filename)
                    current_original_image = pil_image
                    
                    # Create a quick thumbnail for UI reset (optional, but good practice)
                    window["-SAVE-"].update(disabled=True)
                    sg.popup_quick_message("Image Loaded. Click 'Process Preview' to dither.", background_color="#333333", text_color="white")
                except Exception as e:
                    sg.popup_error(f"Error loading image: {e}")

        # 2. Process Image (Resize -> Contrast -> Dither)
        if event == "Process Preview" and current_original_image:
            try:
                # A. Resize
                target_w = int(values["-WIDTH-"])
                aspect_ratio = current_original_image.height / current_original_image.width
                target_h = int(target_w * aspect_ratio)
                
                # Resize utilizing high quality resampling
                working_img = current_original_image.resize((target_w, target_h), Image.Resampling.LANCZOS)

                # B. Enhance Contrast
                enhancer = ImageEnhance.Contrast(working_img)
                working_img = enhancer.enhance(values["-CONTRAST-"])

                # C. Dither
                dithered = floyd_steinberg_dither(working_img)
                current_dithered_image = dithered

                # D. Update Display (Draw Circles)
                # To make the circles visible and smooth, we render them at a higher scale
                # then resize down for the UI window.
                render_scale = 4
                render_w = target_w * render_scale
                render_h = target_h * render_scale
                
                # Create white background
                circle_preview = Image.new("L", (render_w, render_h), 255)
                draw = ImageDraw.Draw(circle_preview)
                
                d_pixels = dithered.load()
                
                # Draw circles for every black pixel
                for y in range(dithered.height):
                    for x in range(dithered.width):
                        if d_pixels[x, y] == 0:
                            # Calculate bounding box for the circle
                            x0 = x * render_scale
                            y0 = y * render_scale
                            x1 = x0 + render_scale - 1
                            y1 = y0 + render_scale - 1
                            draw.ellipse((x0, y0, x1, y1), fill=0)
                
                # Resize to fit inside the 400x400 preview area while keeping aspect ratio
                preview_display_size = (400, 400)
                circle_preview.thumbnail(preview_display_size, Image.Resampling.LANCZOS)
                
                img_data = convert_to_bytes(circle_preview)
                window["-IMAGE-"].update(data=img_data)
                window["-SAVE-"].update(disabled=False)
                
            except Exception as e:
                sg.popup_error(f"Error processing: {e}")

        # 3. Save SVG
        if event == "-SAVE-" and current_dithered_image:
            save_path = sg.popup_get_file("Save SVG", save_as=True, file_types=(("SVG Files", "*.svg"),), default_extension=".svg")
            if save_path:
                try:
                    # Parse the mm input
                    dot_mm = float(values["-DOT_MM-"])
                    create_svg(current_dithered_image, save_path, dot_size_mm=dot_mm)
                    sg.popup("Success!", f"SVG saved to:\n{save_path}\n\nScale: 1 pixel = {dot_mm}mm\nStyle: Circles")
                except ValueError:
                    sg.popup_error("Please enter a valid number for Pen Diameter (mm)")
                except Exception as e:
                    sg.popup_error(f"Error saving file: {e}")

    window.close()

if __name__ == "__main__":
    main()