import FreeSimpleGUI as sg
from PIL import Image, ImageEnhance, ImageDraw, ImageOps, ImageChops
import io
import os

def floyd_steinberg_dither(image):
    """
    Applies Floyd-Steinberg dithering to a PIL Image (Grayscale 'L' mode).
    Returns the dithered image in '1' (1-bit) mode.
    0 = Black/Dot, 255 = White/Empty.
    """
    # Ensure image is grayscale
    if image.mode != 'L':
        img = image.convert('L')
    else:
        img = image.copy()
        
    width, height = img.size
    
    # We load pixels into a list of lists (float-compatible)
    flat_data = list(img.getdata())
    pixels = [flat_data[i * width:(i + 1) * width] for i in range(height)]

    for y in range(height):
        for x in range(width):
            old_pixel = pixels[y][x]
            # Threshold at 128
            new_pixel = 255 if old_pixel > 128 else 0
            pixels[y][x] = new_pixel
            
            error = old_pixel - new_pixel

            # Distribute error to neighbors (Floyd-Steinberg kernel)
            if x + 1 < width:
                pixels[y][x + 1] += error * 7 / 16
            if x - 1 >= 0 and y + 1 < height:
                pixels[y + 1][x - 1] += error * 3 / 16
            if y + 1 < height:
                pixels[y + 1][x] += error * 5 / 16
            if x + 1 < width and y + 1 < height:
                pixels[y + 1][x + 1] += error * 1 / 16

    # Reconstruct the image
    new_data = [int(p) for row in pixels for p in row]
    out_img = Image.new('L', (width, height))
    out_img.putdata(new_data)
    
    return out_img.convert('1')

def convert_to_bytes(image):
    """
    Helper to convert PIL image to bytes for FreeSimpleGUI display.
    """
    with io.BytesIO() as bio:
        image.save(bio, format="PNG")
        return bio.getvalue()

def create_svg(image, filepath, dot_size_mm=0.5, color="#000000", offset=(0.0, 0.0)):
    """
    Creates an SVG for a single channel.
    offset: (x, y) tuple to shift the grid by (in pixel units).
    """
    width, height = image.size
    pixels = image.load()
    
    phys_width_mm = width * dot_size_mm
    phys_height_mm = height * dot_size_mm
    
    # SVG content
    svg_content = [
        f'<svg width="{phys_width_mm}mm" height="{phys_height_mm}mm" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">',
        f'<!-- Generated by Python Dither App: {color} layer with offset {offset} -->'
    ]

    offset_x, offset_y = offset

    # Body
    for y in range(height):
        for x in range(width):
            # In '1' mode, 0 is black (dot), 1/255 is white (no dot)
            if pixels[x, y] == 0:
                # We apply the offset to the circle center.
                # Standard center is x + 0.5. With offset: x + 0.5 + offset_x
                cx = x + 0.5 + offset_x
                cy = y + 0.5 + offset_y
                
                circle = f'<circle cx="{cx}" cy="{cy}" r="0.05" fill="{color}" />'
                svg_content.append(circle)

    # Footer
    svg_content.append('</svg>')
    
    with open(filepath, 'w') as f:
        f.write("\n".join(svg_content))

def process_cmyk(image):
    """
    Splits image into CMYK using 100% GCR (Gray Component Replacement).
    This maximizes the usage of Black (K) and removes that density from C, M, and Y.
    """
    # 1. Prepare RGB image (Handle transparency)
    img = image.convert('RGBA')
    background = Image.new('RGBA', img.size, (255, 255, 255))
    rgb_img = Image.alpha_composite(background, img).convert('RGB')
    
    r, g, b = rgb_img.split()
    
    # 2. Calculate Ink Density (0=Paper, 255=Full Ink)
    # The inverse of RGB is the theoretical max ink for that channel
    c_ink = ImageOps.invert(r)
    m_ink = ImageOps.invert(g)
    y_ink = ImageOps.invert(b)
    
    # 3. Calculate K (Black) as the common darkness shared by all 3 colors
    # K = min(C, M, Y)
    k_ink = ImageChops.darker(c_ink, m_ink)
    k_ink = ImageChops.darker(k_ink, y_ink)
    
    # 4. Remove the K component from C, M, Y (GCR)
    # New C = Old C - K
    c_ink = ImageChops.subtract(c_ink, k_ink)
    m_ink = ImageChops.subtract(m_ink, k_ink)
    y_ink = ImageChops.subtract(y_ink, k_ink)
    
    # 5. Invert back to Lightness (0=Black/Ink, 255=White/Paper) for the ditherer
    # The dither function expects 0 to be a dot, 255 to be empty space.
    c = ImageOps.invert(c_ink)
    m = ImageOps.invert(m_ink)
    y = ImageOps.invert(y_ink)
    k = ImageOps.invert(k_ink)
    
    return {
        'cyan': floyd_steinberg_dither(c),
        'magenta': floyd_steinberg_dither(m),
        'yellow': floyd_steinberg_dither(y),
        'black': floyd_steinberg_dither(k)
    }

def update_preview_display(window, dither_result, is_cmyk, active_channels=None, channel_offset=0.0):
    """
    Regenerates the preview image based on the current dither result and settings.
    This handles the drawing of circles and resizing for the UI.
    channel_offset: The pixel shift applied to separate layers.
    """
    if dither_result is None:
        return

    # Determine dimensions from one of the result images
    if is_cmyk:
        ref_img = dither_result['cyan']
    else:
        ref_img = dither_result

    target_w, target_h = ref_img.size
    
    # Prep for circle rendering (render high res, then downscale)
    render_scale = 4
    render_w = target_w * render_scale
    render_h = target_h * render_scale
    
    # Pad render area slightly to account for offsets so dots don't clip at edges
    # (Optional, but good for preview accuracy)
    
    if is_cmyk:
        # Create CMYK Ink Simulation (Multiply Blend)
        # Start with White Background
        final_preview = Image.new("RGB", (render_w, render_h), (255, 255, 255))
        
        colors = {
            'cyan': (0, 255, 255),
            'magenta': (255, 0, 255),
            'yellow': (255, 255, 0),
            'black': (0, 0, 0)
        }
        
        # Define offsets per channel to create a rosette-like pattern
        # C: 0, 0
        # M: +offset, 0
        # Y: 0, +offset
        # K: +offset, +offset
        offsets = {
            'cyan': (0.0, 0.0),
            'magenta': (channel_offset, 0.0),
            'yellow': (0.0, channel_offset),
            'black': (channel_offset, channel_offset)
        }
        
        # Process each channel as a layer
        for channel, dithered_img in dither_result.items():
            if active_channels and not active_channels.get(channel, True):
                continue

            layer = Image.new("RGB", (render_w, render_h), (255, 255, 255))
            draw = ImageDraw.Draw(layer)
            
            pixels = dithered_img.load()
            w, h = dithered_img.size
            
            off_x, off_y = offsets[channel]
            
            for y in range(h):
                for x in range(w):
                    if pixels[x, y] == 0:
                        # Apply Offset scaled by render_scale
                        x_base = x + off_x
                        y_base = y + off_y
                        
                        x0 = x_base * render_scale
                        y0 = y_base * render_scale
                        x1 = x0 + render_scale - 1
                        y1 = y0 + render_scale - 1
                        draw.ellipse((x0, y0, x1, y1), fill=colors[channel])
            
            # Multiply this layer onto the final composition
            final_preview = ImageChops.multiply(final_preview, layer)
        
        # Use thumbnail to PRESERVE ASPECT RATIO
        preview_img = final_preview.copy()
        preview_img.thumbnail((400, 400), Image.Resampling.LANCZOS)

    else:
        # BW Mode
        circle_preview = Image.new("L", (render_w, render_h), 255)
        draw = ImageDraw.Draw(circle_preview)
        pixels = dither_result.load()
        
        for y in range(dither_result.height):
            for x in range(dither_result.width):
                if pixels[x, y] == 0:
                    x0 = x * render_scale
                    y0 = y * render_scale
                    x1 = x0 + render_scale - 1
                    y1 = y0 + render_scale - 1
                    draw.ellipse((x0, y0, x1, y1), fill=0)
                    
        preview_img = circle_preview.copy()
        preview_img.thumbnail((400, 400), Image.Resampling.LANCZOS)

    # D. Update UI
    img_data = convert_to_bytes(preview_img)
    window["-IMAGE-"].update(data=img_data)
    window["-SAVE-"].update(disabled=False)

def main():
    sg.theme('DarkGrey9')

    layout = [
        [sg.Text("Dither to SVG Converter", font=("Helvetica", 16))],
        
        # File Selection
        [sg.Text("Select Image:"), sg.Input(key="-FILE-", enable_events=True), 
         sg.FileBrowse(file_types=(("All Files", "*.*"), ("JPG", "*.jpg"), ("PNG", "*.png")))],
        
        [sg.HorizontalSeparator()],
        
        # Controls Column
        [sg.Column([
            [sg.Text("Settings", font=("Helvetica", 12, "bold"))],
            
            [sg.Text("Mode:")],
            [sg.Radio("Grayscale", "MODE", default=True, key="-MODE_BW-", enable_events=True),
             sg.Radio("CMYK (4 Files)", "MODE", key="-MODE_CMYK-", enable_events=True)],
            
            # Channel Toggles
            [sg.Text("Preview Channels:", key="-LBL_CH-", visible=False, font=("Helvetica", 9, "italic"))],
            [sg.Checkbox("C", default=True, key="-SHOW_C-", enable_events=True, text_color="cyan", background_color="#333", visible=False),
             sg.Checkbox("M", default=True, key="-SHOW_M-", enable_events=True, text_color="magenta", background_color="#333", visible=False),
             sg.Checkbox("Y", default=True, key="-SHOW_Y-", enable_events=True, text_color="yellow", background_color="#333", visible=False),
             sg.Checkbox("K", default=True, key="-SHOW_K-", enable_events=True, text_color="white", background_color="#333", visible=False)],
             
            [sg.Text("Resize Width (px):")],
            [sg.Slider(range=(50, 800), default_value=200, orientation='h', size=(30, 20), key="-WIDTH-", enable_events=True)],
            
            [sg.Text("Contrast:")],
            [sg.Slider(range=(0.5, 3.0), default_value=1.0, resolution=0.1, orientation='h', size=(30, 20), key="-CONTRAST-", enable_events=True)],
            
            # New Offset Slider
            [sg.Text("Channel Offset (px):", tooltip="Shifts layers to avoid dot overlap")],
            [sg.Slider(range=(0.0, 3.0), default_value=0.5, resolution=0.1, orientation='h', size=(30, 20), key="-OFFSET-", enable_events=True)],

            [sg.Button("Process Preview", size=(20, 2), button_color=("white", "#007acc"))],
            [sg.HorizontalSeparator()],
            [sg.Text("Output Settings", font=("Helvetica", 12, "bold"))],
            [sg.Text("Pen/Dot Diameter (mm):"), sg.Input("0.5", size=(5,1), key="-DOT_MM-")],
            [sg.Button("Save SVG(s)", size=(20, 2), button_color=("white", "green"), disabled=True, key="-SAVE-")]
        ], vertical_alignment='top'),
         
         # Preview Column
         sg.VSeparator(),
         sg.Column([
             [sg.Text("Preview:")],
             [sg.Image(key="-IMAGE-", size=(400, 400), background_color='black')]
         ], element_justification='center', expand_x=True, expand_y=True)
        ]
    ]

    window = sg.Window("Dither Master", layout, resizable=True)

    # State variables
    current_original_image = None
    current_dither_result = None 

    while True:
        event, values = window.read()

        if event == sg.WIN_CLOSED:
            break

        # Helper to get current active channels
        def get_active_channels():
            return {
                'cyan': values["-SHOW_C-"],
                'magenta': values["-SHOW_M-"],
                'yellow': values["-SHOW_Y-"],
                'black': values["-SHOW_K-"]
            }

        # 0. Handle Mode Switch (Show/Hide Checkboxes)
        if event == "-MODE_CMYK-":
            window["-LBL_CH-"].update(visible=True)
            window["-SHOW_C-"].update(visible=True)
            window["-SHOW_M-"].update(visible=True)
            window["-SHOW_Y-"].update(visible=True)
            window["-SHOW_K-"].update(visible=True)
            if current_dither_result and isinstance(current_dither_result, dict):
                 update_preview_display(window, current_dither_result, True, get_active_channels(), values["-OFFSET-"])

        if event == "-MODE_BW-":
            window["-LBL_CH-"].update(visible=False)
            window["-SHOW_C-"].update(visible=False)
            window["-SHOW_M-"].update(visible=False)
            window["-SHOW_Y-"].update(visible=False)
            window["-SHOW_K-"].update(visible=False)
            if current_dither_result and not isinstance(current_dither_result, dict):
                update_preview_display(window, current_dither_result, False)

        # 0.5 Handle Channel Toggles or Offset Change (Immediate Update)
        if event in ("-SHOW_C-", "-SHOW_M-", "-SHOW_Y-", "-SHOW_K-", "-OFFSET-"):
            if current_dither_result and isinstance(current_dither_result, dict):
                update_preview_display(window, current_dither_result, True, get_active_channels(), values["-OFFSET-"])

        # 1. Load Image
        if event == "-FILE-" and values["-FILE-"]:
            filename = values["-FILE-"]
            if os.path.exists(filename):
                try:
                    pil_image = Image.open(filename)
                    current_original_image = pil_image
                    window["-SAVE-"].update(disabled=True)
                    sg.popup_quick_message("Image Loaded. Click 'Process Preview'.", background_color="#333333", text_color="white")
                except Exception as e:
                    sg.popup_error(f"Error loading image: {e}")

        # 2. Process Image
        if event == "Process Preview" and current_original_image:
            try:
                # A. Resize
                target_w = int(values["-WIDTH-"])
                aspect_ratio = current_original_image.height / current_original_image.width
                target_h = int(target_w * aspect_ratio)
                
                working_img = current_original_image.resize((target_w, target_h), Image.Resampling.LANCZOS)
                
                # B. Enhance Contrast (Applied to RGB before splitting helps vibrancy)
                enhancer = ImageEnhance.Contrast(working_img)
                working_img = enhancer.enhance(values["-CONTRAST-"])

                # C. Mode Selection
                is_cmyk = values["-MODE_CMYK-"]
                
                if is_cmyk:
                    # Dither 4 channels
                    current_dither_result = process_cmyk(working_img)
                    update_preview_display(window, current_dither_result, True, get_active_channels(), values["-OFFSET-"])
                else:
                    # BW Mode
                    current_dither_result = floyd_steinberg_dither(working_img)
                    update_preview_display(window, current_dither_result, False)
                
            except Exception as e:
                sg.popup_error(f"Error processing: {e}")

        # 3. Save SVG
        if event == "-SAVE-" and current_dither_result:
            save_path = sg.popup_get_file("Save SVG (Base Filename)", save_as=True, file_types=(("SVG Files", "*.svg"),), default_extension=".svg")
            if save_path:
                try:
                    dot_mm = float(values["-DOT_MM-"])
                    offset_val = float(values["-OFFSET-"])
                    
                    base_dir = os.path.dirname(save_path)
                    base_name = os.path.splitext(os.path.basename(save_path))[0]
                    
                    if isinstance(current_dither_result, dict):
                        # CMYK Save
                        colors = {
                            'cyan': '#00FFFF', 
                            'magenta': '#FF00FF', 
                            'yellow': '#FFD700', 
                            'black': '#000000'
                        }
                        
                        # Define offsets matching the preview logic
                        offsets = {
                            'cyan': (0.0, 0.0),
                            'magenta': (offset_val, 0.0),
                            'yellow': (0.0, offset_val),
                            'black': (offset_val, offset_val)
                        }
                        
                        saved_files = []
                        for channel, img in current_dither_result.items():
                            fn = os.path.join(base_dir, f"{base_name}_{channel}.svg")
                            # Pass the specific offset for this channel
                            create_svg(img, fn, dot_size_mm=dot_mm, color=colors[channel], offset=offsets[channel])
                            saved_files.append(f"- {channel}: {os.path.basename(fn)}")
                            
                        sg.popup("CMYK Export Successful!", "Saved 4 files with offsets:\n" + "\n".join(saved_files))
                        
                    else:
                        # BW Save (No offset needed for single layer)
                        create_svg(current_dither_result, save_path, dot_size_mm=dot_mm, color="#000000")
                        sg.popup("Success!", f"Saved: {save_path}")
                        
                except ValueError:
                    sg.popup_error("Please enter a valid number for Pen Diameter")
                except Exception as e:
                    sg.popup_error(f"Error saving: {e}")

    window.close()

if __name__ == "__main__":
    main()